version: '2.4'

services:
  webpawn:
    build:
      context: .
      dockerfile: Dockerfile
    image: beevo/webpawn
    restart: always
    volumes: 
    - ./src:/usr/src/app
    ports:
    - 666:5000
    environment:
    - ENV=development
